FROM dev.hub.init6.com.pl:5000/php-core.ubuntu.amd64:dev-1.0.0

ARG php=php-8.1.1
WORKDIR /usr/src

RUN curl -O https://www.php.net/distributions/${php}.tar.gz \
 && curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
 && chmod +x wp-cli.phar \
 && mv wp-cli.phar /usr/local/bin/wp \
 && tar vxf ${php}.tar.gz \
 && cd /usr/src/${php} &&./configure --prefix=/usr/local/${php} \
 && make -j8 \ 
 && make install  
