FROM dev.hub.init6.com.pl:5000/php-8.2-fpm.ubuntu.arm64:dev-0.1.13 AS php
FROM dev.hub.init6.com.pl:5000/httpd.ubuntu.arm64:dev-0.1.6 AS apache

FROM ubuntu:latest


COPY --from=apache /usr/local/apache2 /usr/local/apache2
COPY --from=apache /usr/lib/aarch64-linux-gnu/libapr-1.so.0 /usr/lib/aarch64-linux-gnu/libapr-1.so.0
COPY --from=apache /usr/lib/aarch64-linux-gnu/libaprutil-1.so.0 /usr/lib/aarch64-linux-gnu/libaprutil-1.so.0
COPY --from=apache /lib/aarch64-linux-gnu/libexpat.so.1 /lib/aarch64-linux-gnu/libexpat.so.1
COPY --from=apache /usr/bin/supervisord /usr/bin/supervisord
COPY --from=apache /usr/bin/supervisorctl /usr/bin/supervisorctl
COPY --from=apache /etc/supervisor/supervisord.conf /etc/supervisor/supervisord.conf
COPY --from=apache /usr/bin/inotifywait /usr/bin/inotifywait

COPY --from=apache /usr/bin/python3  /usr/bin/python3
COPY --from=apache /usr/lib/python3.9 /usr/lib/python3.9
COPY --from=apache /usr/lib/python3 /usr/lib/python3
COPY --from=apache /usr/lib/python3/dist-packages/supervisor/ /usr/lib/python3/dist-packages/supervisor/


COPY --from=apache /etc/supervisor/conf.d/apache.conf /etc/supervisor/conf.d/apache.conf

COPY --from=php /usr/local/etc/php /usr/local/etc/php
COPY --from=php /usr/local/etc/php-fpm.conf /usr/local/etc/php-fpm.conf
COPY --from=php /usr/local/etc/php-fpm.d /usr/local/etc/php-fpm.d
COPY --from=php /usr/local/sbin/php-fpm /usr/local/sbin/php-fpm
COPY --from=php /usr/local/bin/php /usr/local/bin/php
COPY --from=php /usr/local/include/php /usr/local/include/php
COPY --from=php /usr/local/lib/php /usr/local/lib/php
COPY --from=php /usr/local/php /usr/local/php
COPY --from=php /usr/local/php/php /usr/local/php/php


COPY --from=php /lib/aarch64-linux-gnu/libreadline.so.8 /lib/aarch64-linux-gnu/libreadline.so.8
COPY --from=php /usr/lib/aarch64-linux-gnu/libxml2.so.2 /usr/lib/aarch64-linux-gnu/libxml2.so.2
COPY --from=php /usr/lib/aarch64-linux-gnu/libssl.so.1.1 /usr/lib/aarch64-linux-gnu/libssl.so.1.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1 /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libsqlite3.so.0 /usr/lib/aarch64-linux-gnu/libsqlite3.so.0
COPY --from=php /usr/lib/aarch64-linux-gnu/libcurl.so.4 /usr/lib/aarch64-linux-gnu/libcurl.so.4
COPY --from=php /usr/lib/aarch64-linux-gnu/libonig.so.5 /usr/lib/aarch64-linux-gnu/libonig.so.5
COPY --from=php /usr/lib/aarch64-linux-gnu/libargon2.so.1 /usr/lib/aarch64-linux-gnu/libargon2.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libicuuc.so.67 /usr/lib/aarch64-linux-gnu/libicuuc.so.67
COPY --from=php /usr/lib/aarch64-linux-gnu/libnghttp2.so.14 /usr/lib/aarch64-linux-gnu/libnghttp2.so.14
COPY --from=php /usr/lib/aarch64-linux-gnu/librtmp.so.1 /usr/lib/aarch64-linux-gnu/librtmp.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libssh2.so.1 /usr/lib/aarch64-linux-gnu/libssh2.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libpsl.so.5 /usr/lib/aarch64-linux-gnu/libpsl.so.5
COPY --from=php /usr/lib/aarch64-linux-gnu/libldap_r-2.4.so.2 /usr/lib/aarch64-linux-gnu/libldap_r-2.4.so.2
COPY --from=php /usr/lib/aarch64-linux-gnu/libbrotlidec.so.1 /usr/lib/aarch64-linux-gnu/libbrotlidec.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/liblber-2.4.so.2 /usr/lib/aarch64-linux-gnu/liblber-2.4.so.2 
COPY --from=php /usr/lib/aarch64-linux-gnu/libicudata.so.67  /usr/lib/aarch64-linux-gnu/libicudata.so.67
COPY --from=php /usr/lib/aarch64-linux-gnu/libsasl2.so.2  /usr/lib/aarch64-linux-gnu/libsasl2.so.2
COPY --from=php /usr/lib/aarch64-linux-gnu/libbrotlicommon.so.1  /usr/lib/aarch64-linux-gnu/libbrotlicommon.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libpng16.so.16 /usr/lib/aarch64-linux-gnu/libpng16.so.16
COPY --from=php /usr/lib/aarch64-linux-gnu/libjpeg.so.62 /usr/lib/aarch64-linux-gnu/libjpeg.so.62
COPY --from=php /usr/lib/aarch64-linux-gnu/libfreetype.so.6 /usr/lib/aarch64-linux-gnu/libfreetype.so.6
COPY --from=php /usr/lib/aarch64-linux-gnu/libgomp.so.1 /usr/lib/aarch64-linux-gnu/libgomp.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libMagickWand-6.Q16.so.6 /usr/lib/aarch64-linux-gnu/libMagickWand-6.Q16.so.6 
COPY --from=php /usr/lib/aarch64-linux-gnu/libMagickCore-6.Q16.so.6 /usr/lib/aarch64-linux-gnu/libMagickCore-6.Q16.so.6
COPY --from=php /usr/lib/aarch64-linux-gnu/libzip.so.4 /usr/lib/aarch64-linux-gnu/libzip.so.4
COPY --from=php /usr/lib/aarch64-linux-gnu/libsodium.so.23 /usr/lib/aarch64-linux-gnu/libsodium.so.23
COPY --from=php /usr/lib/aarch64-linux-gnu/libicuio.so.67 /usr/lib/aarch64-linux-gnu/libicuio.so.67
COPY --from=php /usr/lib/aarch64-linux-gnu/libicui18n.so.67  /usr/lib/aarch64-linux-gnu/libicui18n.so.67
COPY --from=php /usr/lib/aarch64-linux-gnu/libX11.so.6 /usr/lib/aarch64-linux-gnu/libX11.so.6
COPY --from=php /usr/lib/aarch64-linux-gnu/liblcms2.so.2 /usr/lib/aarch64-linux-gnu/liblcms2.so.2
COPY --from=php /usr/lib/aarch64-linux-gnu/liblqr-1.so.0 /usr/lib/aarch64-linux-gnu/liblqr-1.so.0
COPY --from=php /usr/lib/aarch64-linux-gnu/libfftw3.so.3 /usr/lib/aarch64-linux-gnu/libfftw3.so.3
COPY --from=php /usr/lib/aarch64-linux-gnu/libfontconfig.so.1 /usr/lib/aarch64-linux-gnu/libfontconfig.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libXext.so.6 /usr/lib/aarch64-linux-gnu/libXext.so.6
COPY --from=php /usr/lib/aarch64-linux-gnu/libltdl.so.7 /usr/lib/aarch64-linux-gnu/libltdl.so.7
COPY --from=php /usr/lib/aarch64-linux-gnu/libxcb.so.1  /usr/lib/aarch64-linux-gnu/libxcb.so.1
COPY --from=php /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0 /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0
COPY --from=php /usr/lib/aarch64-linux-gnu/libXau.so.6 /usr/lib/aarch64-linux-gnu/libXau.so.6
COPY --from=php /usr/lib/aarch64-linux-gnu/libXdmcp.so.6 /usr/lib/aarch64-linux-gnu/libXdmcp.so.6
COPY --from=php /usr/lib/aarch64-linux-gnu/libbsd.so.0 /usr/lib/aarch64-linux-gnu/libbsd.so.0
COPY --from=php /usr/lib/aarch64-linux-gnu/libmd.so.0 /usr/lib/aarch64-linux-gnu/libmd.so.0
COPY --from=php /usr/lib/aarch64-linux-gnu/libinotifytools.so.0 /usr/lib/aarch64-linux-gnu/libinotifytools.so.0

COPY --from=php /etc/supervisor/conf.d/fpm.conf /etc/supervisor/conf.d/fpm.conf
COPY notify_apache.sh notify_fpm.sh /usr/local/sbin/
RUN mkdir /var/log/supervisor/ \
 && echo "[program:notify_apache]"  > /etc/supervisor/conf.d/notify_apache.conf \
 && echo "command=/usr/local/sbin/notify_apache.sh" >> /etc/supervisor/conf.d/notify_apache.conf \
 && echo "[program:notify_fpm]"  > /etc/supervisor/conf.d/notify_fpm.conf \
 && echo "command=/usr/local/sbin/notify_fpm.sh" >> /etc/supervisor/conf.d/notify_fpm.conf


EXPOSE 80
CMD ["/usr/bin/supervisord","-n", "-c","/etc/supervisor/supervisord.conf"]

