FROM dev.hub.init6.com.pl:5000/php-8.2-fpm.ubuntu.amd64:dev-0.1.13 AS php
FROM dev.hub.init6.com.pl:5000/httpd.ubuntu.amd64:dev-0.1.6 AS apache

FROM ubuntu:latest


COPY --from=apache /usr/local/apache2 /usr/local/apache2
COPY --from=apache /usr/lib/x86_64-linux-gnu/libapr-1.so.0 /usr/lib/x86_64-linux-gnu/libapr-1.so.0
COPY --from=apache /usr/lib/x86_64-linux-gnu/libaprutil-1.so.0 /usr/lib/x86_64-linux-gnu/libaprutil-1.so.0
COPY --from=apache /lib/x86_64-linux-gnu/libexpat.so.1 /lib/x86_64-linux-gnu/libexpat.so.1
COPY --from=apache /usr/bin/supervisord /usr/bin/supervisord
COPY --from=apache /usr/bin/supervisorctl /usr/bin/supervisorctl
COPY --from=apache /usr/bin/supervisorctl /usr/bin/supervisorctl
COPY --from=apache /etc/supervisor/conf.d /etc/supervisor/conf.d

COPY --from=php /usr/local/etc/php /usr/local/etc/php
COPY --from=php /usr/local/etc/php-fpm.conf /usr/local/etc/php-fpm.conf
COPY --from=php /usr/local/etc/php-fpm.d /usr/local/etc/php-fpm.d
COPY --from=php /usr/local/sbin/php-fpm /usr/local/sbin/php-fpm
COPY --from=php /usr/local/bin/php /usr/local/bin/php
COPY --from=php /usr/local/include/php /usr/local/include/php
COPY --from=php /usr/local/lib/php /usr/local/lib/php
COPY --from=php /usr/local/php /usr/local/php
COPY --from=php /usr/local/php/php /usr/local/php/php


COPY --from=php /lib/x86_64-linux-gnu/libreadline.so.8 /lib/x86_64-linux-gnu/libreadline.so.8
COPY --from=php /usr/lib/x86_64-linux-gnu/libxml2.so.2 /usr/lib/x86_64-linux-gnu/libxml2.so.2
COPY --from=php /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/libssl.so.1.1
COPY --from=php /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
COPY --from=php /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
COPY --from=php /usr/lib/x86_64-linux-gnu/libcurl.so.4 /usr/lib/x86_64-linux-gnu/libcurl.so.4
COPY --from=php /usr/lib/x86_64-linux-gnu/libonig.so.5 /usr/lib/x86_64-linux-gnu/libonig.so.5
COPY --from=php /usr/lib/x86_64-linux-gnu/libargon2.so.1 /usr/lib/x86_64-linux-gnu/libargon2.so.1
COPY --from=php /usr/lib/x86_64-linux-gnu/libicuuc.so.67 /usr/lib/x86_64-linux-gnu/libicuuc.so.67



#CMD ["/usr/local/sbin/nginx", "-g", "daemon off;"]
